<!DOCTYPE html>
<html>
<head>
    <title>Invoice</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .content {
            margin: 20px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        .table th {
            background-color: #f4f4f4;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #555;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Invoice</h1>
        <p>Invoice Number: <strong>{{ $invoice->number }}</strong></p>
    </div>

    <div class="content">
        <p><strong>Patient Name:</strong> {{ $patientName }}</p>
        <p><strong>Treatment:</strong> {{ $treatmentName }}</p>
        <p><strong>Date:</strong> {{ $date }}</p>
        <p><strong>Amount:</strong> ${{ number_format($amount, 2) }}</p>
        <p><strong>Status:</strong> {{ ucfirst($status) }}</p>

        <h3>Thank you for your payment!</h3>
    </div>

    <div class="footer">
        <p>Invoice generated by Your Company Name</p>
    </div>
</body>
</html>
